### PR TITLE
add IgnorePointer to OverlayTutorialBackbone.

### PR DESCRIPTION
**Pull request by Guang1234567**
Hello dev:

The PR as title said.

Thanks.

### CODE REVIEW

**Comment by TabooSun** [comment]
Can you explain in more detail why this is needed? I don't see supporting this is helpful, you can just wrap your widget with `IgnorePointer` after wrapping with `OverlayTutorialScope`, and in this way, you get more control, as in you can use `AbsorbPointer` if you need it to be visible in hit test.

**Comment by Guang1234567** [comment]
@TabooSun 

> Can you explain in more detail why this is needed? I don't see supporting this is helpful, you can just wrap your widget with IgnorePointer after wrapping with OverlayTutorialScope, and in this way, you get more control, as in you can use AbsorbPointer if you need it to be visible in hit test.

In my case,  my app UI has `Button (name "next step")` in `OverlayTutorialHit`.

so wrapping `OverlayTutorialScope` with `IgnorePointer` will cause the `Button (name "next step")` cannot be clicked.

**Comment by TabooSun** [comment]
Hmm, can you try wrapping `IgnorePointer` with `OverlayTutorialScope` instead?

This is how I did for my project, and it works great for me.

**Comment by TabooSun** [comment]
I don't receive your response until now. Hence, I am going to close this PR. 

I believe the comment I gave works for you. If you disagree, reopen this PR.

**Pull request closed without merging**
