### PR TITLE
Fixes #26

### LINKED ISSUE #26: How to make the overlay disappear when the user clicks anywhere on the modal overlay?
Maybe I'm doing it wrong, but I'm testing the plugin and I leave a cutout for the button which makes it appear and that button make it disappear as well. However I'd like the overlay to disappear if the user clicks anywhere on the overlay. And I'd also like the cutout buttons to not function while the overlay is up.

### PR DESCRIPTION
**Pull request by MrCsabaToth**
Let's talk about how this could be merge quality. I'm defaulting to `absorbPointer = false` to preserve backwards compatibility. I needed to make `bool enabled;` mutable.

### CODE REVIEW

**Comment by TabooSun** [comment]
Can you explain more about how this PR would be helpful? 

The reason I am not willing to take this was being answered in [here](https://github.com/TabooSun/overlay_tutorial/pull/22#issuecomment-859161155). You can see the PR you suggest is using `AbsorbPointer`, whereas the PR previously suggested `IgnorePointer`. This will be an unnecessary workload for maintaining this package if we want to include both of these to suit the community's needs.

Plus, if the code I suggested in the issue work for you, there is no need to update this package as well,
Below is a revision of the suggested code:

```dart
// Value can be changed here to toggle the Overlay Tutorial.
final enabled = true;

return GestureDetector(
      onTap: enabled ? () {
        print("Close overlay here.");
      } : null,
      child: OverlayTutorialScope(
        enabled: enabled,
        child: AbsorbPointer(
          absorbing: enabled,
          child: Scaffold(
            appBar: AppBar(
              title: Text(widget.title),
            ),
            body: Center(
              child: OverlayTutorialHole(
                enabled: enabled,
                overlayTutorialEntry: OverlayTutorialRectEntry(
                  padding: const EdgeInsets.symmetric(horizontal: 8.0),
                  radius: const Radius.circular(16.0),
                ),
                child: OutlinedButton(
                  onPressed: () {
                    print('Inner button pressed');
                  },
                  child: Text('Inner button'),
                ),
              ),
            ),
          ),
        ),
      ),
    );
```

**Comment by MrCsabaToth** [comment]
Actually the IgnorePointer vs AbsorbPointer doesn't matter to me much. I could rewrite my PR to use IgnorePointer, however right now I'm not even sure that my fork is needed at all. Since I brought in GestureDetector, I'm trying to do that purely from my application, outside of your plugin. This way my use-case could be out-of-scope for your plugin. I'll report back.

**Comment by TabooSun** [comment]
To be honest, it does not really matter whether or not this PR is supporting one of `IgnorePointer` or `AbsorbPointer`,  it's about whether or not 
- to support both `IgnorePointer` and `AbsorbPointer`
- DO NOT support this at all

I would appreciate that you come back to me and let me know that your use case can be done purely from your application. In this case, we can just proceed to not support this feature at all.

However, if this is not the case, I am happy to work on reviewing this PR. But I would also like you to provide some reproducible code so that I can include it in the package example or even better, in a test.

**Comment by MrCsabaToth** [comment]
So for some reason the `IgnorePointer` does not work for me. The overlay cannot be dismissed as I planned. I had to bring back the `AbsorbPointer` and at the same time I elevated `GestureDetector` out of the plugin into the host application. I'll update the example project so there can be a proper example.

**Comment by TabooSun** [comment]
After doing a few testings, I still don't see the value of supporting this in the package.

According to your code in `overlay_tutorial_scope.dart`, you are basically adding an `AbsorbPointer`:

```dart
_OverlayTutorialBackbone(
  overlayColor: widget.overlayColor,
  enabled: widget.enabled,
  overlayTutorialHoles: _overlayTutorialHoles,
  onEntryRectCalculated: () {
    _updateChildren();
  },
  child: AbsorbPointer(
    absorbing: widget.enabled && widget.absorbPointer,
    ignoringSemantics: true,
    child: widget.child,
  ),
)
``` 
which can be easily done on the end-user side, as such:
```dart
OverlayTutorialScope(
    enabled: _tutorialVisible,
    absorbPointer: _absorbPointer,
    overlayColor: Colors.green.withOpacity(.6),
    child: AbsorbPointer(
      absorbing: _tutorialVisible && _absorbPointer,
      child: SafeArea(
        child: Scaffold(

...other remaining code here
```

I might be missing out the key idea of you doing this. Feel free to point out. Otherwise, I am unable to merge this PR.

**Comment by MrCsabaToth** [comment]
`which can be easily done on the end-user side` - I could bring everything to user-land, so yes. I hope I didn't waste your time much. Maybe a use-case like that could be still added to the examples on another screen.

**Comment by TabooSun** [comment]
`Maybe a use-case like that could be still added to the examples on another screen`

I agree with this. I will include this when I am free.

Otherwise, PR is always welcome.

**Comment by MrCsabaToth** [comment]
@TabooSun my fork has the modified example but that trumps the original example. What do you think what would be the best way to have this use-case? Another screen? How should the user navigate to that screen. I can modify the example for a PR.

**Comment by TabooSun** [comment]
Maybe a screen that starts with 2 buttons saying, `Simple example` and `Example with GestureDetector`?

Just a suggestion, you can do it in any creative way.😄

But we need a separate Issue and PR to track this.

I appreciate in advance for your contribution.

**Pull request closed without merging**
